### PR TITLE
RA-1600: Harvest Growtth Chart Feature For Reff app

### PR DESCRIPTION
**Pull request by mozzy11**
Ticket : https://issues.openmrs.org/browse/RA-1600
* I haversted The Growth Charts into a new Module
* I wrote Tests for the Backend Logic of the feature

### CODE REVIEW

**Comment by kaweesi** [comment]
Can you please reference the isantePlus work in your read me so that its easy to tag the current work wrapped in here to a set of requirements!

**Comment by kaweesi** [comment]
This looks impressive dear @mozzy11 could you please handle the NPE on loading the charts for some patients https://snipboard.io/1CU7Mm.jpg

**Comment by mozzy11** [comment]
Thanks @k-joseph , The  NPE is thrown in case the growth charts tries to load the HeadCircumfrence Concept and is not found.. I did this work here in the reference-metadata
https://github.com/openmrs/openmrs-module-referencemetadata/pull/46/files
to have the  HeadCircumfrence concept added by default in reference-app. 
However let me handle the NPE just incase the HeadCircumfrence Concept is found null

**Comment by mozzy11** [comment]
@kaweesi  , 
* i Updated the PR. handled the NPE , and now a message is displayed to the UI in case Head Circumfrence Concept is not added and configured.
* I also referenced the isanteplus work in the read Me

**Comment by mozzy11** [comment]
Message dispalyed when Head Circumfrence Concept is not found and configured

**Comment by mozzy11** [comment]
hello @kaweesi  , i have attached a screenhot above of the message displayed

**Pull request merged**
